apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bmh-generator-operator.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bmh-generator-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.hpOneView.enabled }}
  ONEVIEW_PASSWORD: {{ .Values.hpOneView.password | quote }}
  HP_BMC_PASSWORD: {{ .Values.hpOneView.bmc.password | quote }}
  {{- end }}
  {{- if .Values.ciscoUCS.enabled }}
  UCS_CENTRAL_PASSWORD: {{ .Values.ciscoUCS.central.password | quote }}
  UCS_MANAGER_PASSWORD: {{ .Values.ciscoUCS.manager.password | quote }}
  CISCO_BMC_PASSWORD: {{ .Values.ciscoUCS.bmc.password | quote }}
  {{- end }}
  {{- if .Values.dellOME.enabled }}
  OME_PASSWORD: {{ .Values.dellOME.password | quote }}
  DELL_BMC_PASSWORD: {{ .Values.dellOME.bmc.password | quote }}
  {{- end }}
