apiVersion: v2
name: bmh-generator-operator
description: A Kubernetes operator that automatically generates BareMetalHost resources from vendor management systems (HP OneView, Cisco UCS, Dell OME)
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - baremetal
  - metal3
  - openshift
  - operator
  - hp-oneview
  - cisco-ucs
  - dell-ome
maintainers:
  - name: Roi Blum
home: https://github.com/roiblum1/BareMetalHostUCS
sources:
  - https://github.com/roiblum1/BareMetalHostUCS
